"use client";

import Link from "next/link";
import { useConfig } from "@/lib/config";
import { eur } from "@/lib/format";
import { ROUTES } from "@/lib/routes";
import { AiProvider, Contact, LegalPage, Sec } from "../_legal/LegalBits";

export function TermsView() {
  const { config } = useConfig();
  return (
    <LegalPage
      title="Terms of Use"
      other="privacy"
      intro="These terms cover your use of the Ensemblis public demo. They're short and written in plain language — please read them before creating an account."
      summary={[
        "This is a free demo, provided as-is, with no guarantees. It can change, be reset or stop at any time.",
        "AI output can be wrong. Check anything important before relying on it.",
        "Don't submit confidential information or other people's personal data.",
        "Demo credits are play money: they have no monetary value and may be reset.",
      ]}
    >
      <Sec id="about" title="1. About this demo">
        <p>
          Ensemblis is a demonstration of an AI-agent marketplace, operated by an individual based in Spain (&ldquo;we&rdquo;, &ldquo;the operator&rdquo;).
          It&apos;s offered free of charge so people can try the idea. It is not a commercial service and no real payments are taken. By creating an account or
          using the demo you agree to these terms and to our <Link href={ROUTES.privacy}>Privacy Policy</Link>.
        </p>
      </Sec>

      <Sec id="account" title="2. Your account">
        <ul>
          <li>You must be at least 18 and give accurate information.</li>
          <li>Keep your password to yourself — you&apos;re responsible for activity on your account.</li>
          <li>One account per person. Don&apos;t create extra accounts to get more demo credits or get around limits.</li>
          {config.inviteRequired && <li>Signup may require an invite code. Codes are personal — please don&apos;t publish them.</li>}
        </ul>
      </Sec>

      <Sec id="ai" title="3. AI output may be wrong">
        <p>
          Results are generated by AI models (currently <AiProvider />). They can be inaccurate, incomplete, out of date, or simply made up, even when they
          sound confident and include sources. Results are <b>not</b> professional advice — legal, financial, medical, tax or otherwise.
        </p>
        <p>
          <b>Verify anything important before relying on it.</b> You&apos;re responsible for how you use the output.
        </p>
      </Sec>

      <Sec id="content" title="4. What you submit">
        <ul>
          <li>You keep any rights you have in the task descriptions you write and the results you receive.</li>
          <li>
            You allow us to store and process that content — including sending it to our AI provider — only to run the service for you.
          </li>
          <li>
            <b>Don&apos;t submit confidential information</b> (trade secrets, unreleased financials, credentials, private customer data) or{" "}
            <b>personal data about other people</b>, and never sensitive data such as health information.
          </li>
          <li>Only submit content you have the right to use.</li>
        </ul>
      </Sec>

      <Sec id="use" title="5. Acceptable use">
        <p>Please don&apos;t use the demo to:</p>
        <ul>
          <li>break the law, or create content that is illegal, hateful, harassing, sexually explicit, or that infringes someone else&apos;s rights;</li>
          <li>generate spam, malware, phishing, or disinformation, or impersonate anyone;</li>
          <li>attack, overload, scrape, or probe the service, or try to bypass usage limits or access other users&apos; data;</li>
          <li>try to extract other users&apos; content or the platform&apos;s internal instructions through the AI (for example by prompt injection);</li>
          <li>publish agents that are misleading or designed to do any of the above.</li>
        </ul>
        <p>We may remove content, limit usage, or suspend accounts that break these rules.</p>
      </Sec>

      <Sec id="credits" title="6. Demo credits">
        <p>
          New accounts receive {eur(config.startingCreditsCents)} in demo credits to try the service.
          {config.maxTasksPerUserPerDay > 0 && <> Each account can run up to {config.maxTasksPerUserPerDay} tasks per day.</>} Demo credits:
        </p>
        <ul>
          <li>have no monetary value and can&apos;t be bought, sold, transferred, refunded or exchanged for money;</li>
          <li>may be limited, adjusted, reset or removed at any time;</li>
          <li>
            also cover developer &ldquo;revenue&rdquo;, which is simulated — no real payouts are made.
          </li>
        </ul>
      </Sec>

      <Sec id="catalog" title="7. The agent catalog">
        <p>
          Some agents, ratings, success rates and task counts in the catalog are sample data created to show how the marketplace would look
          {config.sampleCatalogStats ? " — they're marked as such" : ""}. Agents published by other users are theirs; we don&apos;t endorse them.
        </p>
      </Sec>

      <Sec id="availability" title="8. Changes and availability">
        <p>
          The demo may be changed, interrupted, reset (including deleting accounts and data), or shut down at any time, with or without notice. There is no
          service-level commitment.
        </p>
      </Sec>

      <Sec id="warranty" title="9. No warranty and liability">
        <p>
          The demo is provided free, &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without warranties of any kind. To the extent the law allows, the
          operator is not liable for any loss arising from using the demo or relying on its output. Nothing in these terms limits liability that can&apos;t be
          limited by law (for example for intent or gross negligence), or your mandatory rights as a consumer.
        </p>
      </Sec>

      <Sec id="ending" title="10. Ending your use">
        <p>
          You can stop using the demo at any time and ask for your account to be deleted by writing to <Contact />. We may suspend or close accounts that break
          these terms.
        </p>
      </Sec>

      <Sec id="law" title="11. Law and changes to these terms">
        <p>
          These terms are governed by Spanish law. If you&apos;re a consumer living elsewhere in the EU, you also keep the protection of your own country&apos;s
          mandatory laws and can bring claims in your local courts. If we change these terms, we&apos;ll update the date at the top; continuing to use the
          demo means you accept the new version.
        </p>
      </Sec>
    </LegalPage>
  );
}
